# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-18 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherData', '0002_auto_20180118_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wind',
            name='speed',
            field=models.CharField(max_length=3),
        ),
    ]
