# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherData', '0003_auto_20180118_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='wind',
            name='stationID',
            field=models.CharField(default='new_station', max_length=20),
        ),
    ]
